### ISSUE TITLE
USB is not detected in AR9331 OlliteV1 16MB Flash

### ISSUE THREAD

**Issue by Arun1295** [GainStrongService/openwrt#1]
USB port is not detected in Ar9331 Atheros board.

In DTS (target/linux/ath79/dts/ar9330.dtsi )Interrupt number 3 is registered for UART as well as USB. We are suspecting this could be the reason.

usb@1b000000 {
                        compatible = "chipidea,usb2";
                        reg = <0x1b000000 0x200>;
                        interrupts = <0x3>;
                        resets = <0x5 0x5>;
                        reset-names = "usb-host";
                        phy-names = "usb-phy";
                        phys = <0xa>;
                        status = "okay";
                };
                
uart@18020000 {
                                compatible = "qca,ar9330-uart";
                                reg = <0x18020000 0x14>;
                                interrupts = <0x3>;
                                clocks = <0x4 0x3>;
                                clock-names = "uart";
                        };

Interrupt:

root@OpenWrt:/proc#
root@OpenWrt:/proc# cat interrupts
           CPU0
  2:     176552      MIPS   2  ath9k
  4:          0      MIPS   4  19000000.eth
  5:      34053      MIPS   5  1a000000.eth
  7:     492710      MIPS   7  timer
  9:      11329      MISC   3  18020000.uart
ERR:         15
                 

root@OpenWrt:/proc# lsusb
root@OpenWrt:/proc#
root@OpenWrt:/proc#
root@OpenWrt:/proc# dmesg | grep ehci
[    6.446976] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    6.477272] ehci-fsl: Freescale EHCI Host controller driver
[    6.485007] ehci-platform: EHCI generic platform driver
[    6.495013] ehci-pci: EHCI PCI platform driver
root@OpenWrt:/proc#

**Comment by guoxiaoqiao** [comment]
Please switch to OpenWrt 22.03 branch
